name: workflow-dispatch-dynamic-matrix
on:
  push:
      branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.dataStep.outputs.myoutput }}
    steps:
      - id: dataStep
        run: |
          TARGETS='["101:399", "401:899"]'
          echo "myoutput=$(jq -cn --argjson environments "$TARGETS" '{target: $environments}')" >> $GITHUB_OUTPUT          
  run-matrix:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.mymatrix) }}
    steps:
      - run: echo ${{matrix.target}}
