name: workflow-dispatch-dynamic-matrix
on:
  push:
      branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      test_matrix: ${{ steps.dataStep.outputs.test_output }}
    steps:
      - id: dataStep
        run: |
          TESTS='["101:399", "401:899"]'
          echo "test_output=$(jq -cn --argjson values "$TESTS" '{test_cases: $values}')" >> $GITHUB_OUTPUT          
  run-matrix:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.test_matrix) }}
    steps:
      - run: echo ${{matrix.test_cases}}
