name: workflow-dispatch-dynamic-matrix
on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      test_matrix: ${{ steps.json.outputs.test_matrix }}
    steps:
      - name: build matrix
        id: json
        run: |
          matrix='{ "test_matrix": ["101","repo2","repo3","401:899"] }'
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  run-matrix:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.test_matrix) }}
    steps:
      - run: echo "${{ matrix.test_matrix }}"
